version: '{build}'

os: Visual Studio 2017

platform:
  - x64
  
configuration:
  - Release
  
environment:
  CMAKE_GENERATOR_NAME: Visual Studio 15 2017 Win64
  CMAKE_BUILD_TYPE: Release

matrix:
  fast_finish: true
  
clone_folder: C:\projects\contest

before_build:
  - cmd: cd C:\projects\contest
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% ..
  
build:
  project: C:\projects\contest\build\contest-template.sln
  parallel: true

test_script:
  - cmd: cd C:\projects\contest\build
  - cmd: ctest --build-config %configuration%

artifacts:
  - path: output\ui_exe_template.exe
    name: ui
