version: '{build}'

os: Visual Studio 2015

platform:
  - x64
  
environment:
  CMAKE_GENERATOR_NAME: Visual Studio 14 2015 Win64

matrix:
  fast_finish: true
  
build_script:
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build .
  
test_script:
  - ctest
