version: '{build}'

os: Visual Studio 2015

platform:
  - x64
  
environment:
  CMAKE_GENERATOR_NAME: Visual Studio 14 2015 Win64
  CMAKE_BUILD_TYPE: Release

matrix:
  fast_finish: true
  
build_script:
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% ..
  - cmd: cmake --build .
  
test_script:
  - cmd: ctest -C %CMAKE_BUILD_TYPE%
